[workspace]
resolver = "2"
members = ["pliron-derive"]

[package]
name = "pliron"
description = "Programming Languages Intermediate RepresentatiON"
version.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[workspace.package]
version = "0.1.7"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/vaivaswatha/pliron"
categories = ["compilers"]
keywords = ["pliron", "llvm", "mlir", "compiler"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pliron-derive = { path = "./pliron-derive" }

slotmap = "1.0.7"
downcast-rs = "1.2.1"
rustc-hash = "1.1.0"
thiserror = "1.0.61"
# clap = "4.1.6"
apint = "0.2.0"
sorted_vector_map = "0.1.0"
linkme = "0.3"
once_cell = "1.19.0"
paste = "1.0"
combine.workspace = true
regex = "1.10.4"
dyn-clone = "1.0.17"

[dev-dependencies]
expect-test.workspace = true

[workspace.dependencies]
expect-test = "1.5.0"
proc-macro2 = "1.0.84"
quote = "1.0.36"
prettyplease = "0.2.20"
syn = { version = "2.0.66", features = ["derive"] }
combine = "4.6.7"
